language: scala

stages:
  - name: build

jobs:
  include:
    - stage: build
      script:
        - mvn clean install -f parent/pom.xml
      before_deploy:
        - cp -R repository/target/repository update
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        local_dir: update
        on:
          branch: master
          tags: true
