language: scala

stages:
  - name: build
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - stage: build
      script:
        - mvn clean verify -f parent/pom.xml
    - stage: release
      script:
        - mvn clean install -f parent/pom.xml
        - cp -R repository/target/repository update
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: false
        local_dir: update
        on:
          branch: master
